# Generated by Django 5.1.3 on 2024-11-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_product_description_en_product_description_kz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_kz',
            new_name='description_kk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name_kz',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_kk',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
